FROM node:18.17-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./

# ENV NODE_ENV=development

RUN npm install
COPY . .



# CMD [ "npm", "run", "serve"]
# EXPOSE 3001
# CMD [ "npm", "run", "dev", "--host 0.0.0.0"]

RUN npm run build

FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]