version: '3.6'
services:
  client:
    container_name: client
    restart: always
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - '80:80'
    depends_on:
      - server
    networks:
      - app-network
  db:
    container_name: postgresql
    image: postgres:latest
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=teste
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    container_name: server
    restart: always
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
volumes:
  db_data:
networks:
  app-network:
    driver: bridge