FROM node:20-alpine3.17
WORKDIR /usr/src/app
ENV DATABASE_URL="postgresql://teste:teste@host.docker.internal:5432/teste?schema=public"
COPY package*.json ./
COPY tsconfig*.json ./
RUN npm install
COPY . .
RUN npm run prisma:initialize
RUN npm run prisma:generate
RUN npm run prisma:install
RUN npm run build
EXPOSE 3000
CMD [ "npm", "run", "start:prod" ]