FROM node:20-alpine3.17
WORKDIR /usr/src/app
COPY package*.json ./
COPY tsconfig*.json ./
RUN npm install
COPY . .
RUN npm run prisma:initialize
RUN npm run prisma:generate
RUN npm run prisma:install
RUN npm run build
EXPOSE 3000
CMD [ "npm", "run", "start:prod" ]

#### tests below
# # FROM node:20-alpine
# FROM node:20-alpine3.17

# WORKDIR /usr/src/app

# COPY package*.json ./
# COPY tsconfig*.json ./

# RUN npm install npm@latest -g
# RUN npm i -g pnpm
# # RUN pnpm i
# RUN npm install

# RUN npm install -g @nestjs/cli
# RUN npm install -g prisma
# # RUN npm install -g @prisma/cli

# # RUN npm install

# # RUN npm run prisma:generate
# RUN npm run prisma:migrate
# RUN mv node_modules ../
# RUN npm cache clean --force 
# COPY . ./
# RUN npm run build
# # RUN pnpm build

# EXPOSE 3000
# # CMD [ "npm", "run", "start:prod" ]
# CMD [ "pnpm", "start:prod" ]
